import { WorkoutPlan } from './workout.model';

export const WORKOUT_PLANS: WorkoutPlan[] = [
  // ========================================
  // UPPER A — CHEST + BALANCED UPPER
  // ========================================
  {
    id: 'upper-a',
    name: 'Upper A',
    label: 'DAY 1',
    exercises: [
      {
        id: 'incline-db-press',
        name: 'Incline DB Press',
        sets: 3,
        minReps: 8,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2,
      },
      {
        id: 'flat-db-press',
        name: 'Flat DB Press',
        sets: 3,
        minReps: 8,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2,
      },
      {
        id: 'lat-pulldown',
        name: 'Lat Pulldown',
        sets: 3,
        minReps: 8,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'seated-cable-row',
        name: 'Seated Cable Row',
        sets: 3,
        minReps: 8,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'lateral-raise',
        name: 'Lateral Raises',
        sets: 3,
        minReps: 12,
        maxReps: 15,
        restSeconds: 60,
        weightIncrement: 1,
      },
      {
        id: 'face-pull',
        name: 'Face Pull',
        sets: 2,
        minReps: 12,
        maxReps: 15,
        restSeconds: 60,
        weightIncrement: 2.5,
      },
      {
        id: 'biceps-curl',
        name: 'Biceps Curl',
        sets: 2,
        minReps: 10,
        maxReps: 12,
        restSeconds: 60,
        weightIncrement: 1,
      },
      {
        id: 'triceps-pushdown',
        name: 'Cable Triceps Pushdown',
        sets: 2,
        minReps: 10,
        maxReps: 12,
        restSeconds: 60,
        weightIncrement: 2.5,
      },
    ],
  },

  // ========================================
  // LOWER — LEGS + RUNNING SUPPORT
  // ========================================
  {
    id: 'lower',
    name: 'Lower',
    label: 'DAY 2',
    exercises: [
      {
        id: 'squat',
        name: 'Squat',
        sets: 3,
        minReps: 6,
        maxReps: 10,
        restSeconds: 120,
        weightIncrement: 2.5,
      },
      {
        id: 'romanian-deadlift',
        name: 'Romanian Deadlift',
        sets: 3,
        minReps: 8,
        maxReps: 10,
        restSeconds: 120,
        weightIncrement: 2.5,
      },
      {
        id: 'leg-press',
        name: 'Leg Press',
        sets: 3,
        minReps: 10,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 5,
      },
      {
        id: 'leg-curl',
        name: 'Leg Curl',
        sets: 2,
        minReps: 10,
        maxReps: 15,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'calf-raise',
        name: 'Calf Raises',
        sets: 3,
        minReps: 12,
        maxReps: 20,
        restSeconds: 60,
        weightIncrement: 2.5,
      },
      {
        id: 'plank',
        name: 'Plank',
        sets: 3,
        minReps: 30,
        maxReps: 60,
        restSeconds: 60,
        weightIncrement: 0,
      },
    ],
  },

  // ========================================
  // UPPER B — BACK + SHOULDERS + CHEST
  // ========================================
  {
    id: 'upper-b',
    name: 'Upper B',
    label: 'DAY 3',
    exercises: [
      {
        id: 'lat-pulldown',
        name: 'Lat Pulldown',
        sets: 3,
        minReps: 8,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 't-bar-row-machine',
        name: 'T-Bar Row Machine',
        sets: 3,
        minReps: 8,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'machine-chest-press',
        name: 'Machine Chest Press',
        sets: 3,
        minReps: 8,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'lateral-raise',
        name: 'Lateral Raises',
        sets: 3,
        minReps: 12,
        maxReps: 15,
        restSeconds: 60,
        weightIncrement: 1,
      },
      {
        id: 'face-pull',
        name: 'Face Pull',
        sets: 2,
        minReps: 12,
        maxReps: 15,
        restSeconds: 60,
        weightIncrement: 2.5,
      },
      {
        id: 'biceps-curl',
        name: 'Biceps Curl',
        sets: 2,
        minReps: 10,
        maxReps: 12,
        restSeconds: 60,
        weightIncrement: 1,
      },
      {
        id: 'triceps-pushdown',
        name: 'Cable Triceps Pushdown',
        sets: 2,
        minReps: 10,
        maxReps: 12,
        restSeconds: 60,
        weightIncrement: 2.5,
      },
    ],
  },
];
