import { WorkoutPlan } from './workout.model';

export const WORKOUT_PLANS: WorkoutPlan[] = [
  // UPPER A
  {
    id: 'upper-a',
    name: 'Upper A',
    label: 'DAY 1',
    exercises: [
      {
        id: 'bb-bench-press',
        name: 'BB Bench Press',
        sets: 4,
        minReps: 6,
        maxReps: 8,
        restSeconds: 120,
        weightIncrement: 2.5,
      },
      {
        id: 'incline-db-press',
        name: 'Incline DB Press',
        sets: 3,
        minReps: 8,
        maxReps: 10,
        restSeconds: 90,
        weightIncrement: 2,
      },
      {
        id: 'lat-pulldown',
        name: 'Lat Pulldown',
        sets: 3,
        minReps: 8,
        maxReps: 10,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'seated-cable-row',
        name: 'Seated Cable Row',
        sets: 3,
        minReps: 10,
        maxReps: 10,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'lateral-raise',
        name: 'Lateral Raises',
        sets: 3,
        minReps: 12,
        maxReps: 15,
        restSeconds: 60,
        weightIncrement: 1,
      },
      {
        id: 'face-pull',
        name: 'Face Pull',
        sets: 3,
        minReps: 12,
        maxReps: 15,
        restSeconds: 60,
        weightIncrement: 2.5,
      },
      {
        id: 'biceps-curl',
        name: 'Biceps Curl',
        sets: 3,
        minReps: 10,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 1,
      },
      {
        id: 'triceps-pushdown',
        name: 'Cable Triceps Pushdown',
        sets: 3,
        minReps: 10,
        maxReps: 15,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
    ],
  },

  // LOWER
  {
    id: 'lower',
    name: 'Lower',
    label: 'DAY 2',
    exercises: [
      {
        id: 'leg-press',
        name: 'Leg Press',
        sets: 4,
        minReps: 8,
        maxReps: 10,
        restSeconds: 120,
        weightIncrement: 5,
      },
      {
        id: 'romanian-deadlift',
        name: 'Romanian Deadlift',
        sets: 3,
        minReps: 8,
        maxReps: 10,
        restSeconds: 120,
        weightIncrement: 2.5,
      },
      {
        id: 'leg-extension',
        name: 'Leg Extension',
        sets: 3,
        minReps: 10,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'leg-curl',
        name: 'Leg Curl',
        sets: 3,
        minReps: 10,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'walking-lunges',
        name: 'Walking Lunges',
        sets: 2,
        minReps: 10,
        maxReps: 10,
        restSeconds: 90,
        weightIncrement: 2,
      },
      {
        id: 'calf-raise',
        name: 'Calf Raises',
        sets: 3,
        minReps: 12,
        maxReps: 15,
        restSeconds: 60,
        weightIncrement: 2.5,
      },
    ],
  },

  // UPPER B
  {
    id: 'upper-b',
    name: 'Upper B',
    label: 'DAY 3',
    exercises: [
      {
        id: 'incline-db-press',
        name: 'Incline DB Press',
        sets: 3,
        minReps: 8,
        maxReps: 10,
        restSeconds: 90,
        weightIncrement: 2,
      },
      {
        id: 'lat-pulldown',
        name: 'Lat Pulldown',
        sets: 3,
        minReps: 8,
        maxReps: 10,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'machine-chest-press',
        name: 'Machine Chest Press',
        sets: 3,
        minReps: 8,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'seated-cable-row',
        name: 'Seated Cable Row',
        sets: 3,
        minReps: 8,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
      {
        id: 'lateral-raise',
        name: 'Lateral Raises',
        sets: 3,
        minReps: 12,
        maxReps: 15,
        restSeconds: 60,
        weightIncrement: 1,
      },
      {
        id: 'face-pull',
        name: 'Face Pull',
        sets: 3,
        minReps: 12,
        maxReps: 15,
        restSeconds: 60,
        weightIncrement: 2.5,
      },
      {
        id: 'hammer-curl',
        name: 'Hammer Curl',
        sets: 3,
        minReps: 10,
        maxReps: 12,
        restSeconds: 90,
        weightIncrement: 1,
      },
      {
        id: 'triceps-pushdown',
        name: 'Cable Triceps Pushdown',
        sets: 3,
        minReps: 10,
        maxReps: 15,
        restSeconds: 90,
        weightIncrement: 2.5,
      },
    ],
  },
];
